- name: "Install node "
  become: yes
  apt:
    name: ["nodejs"]
    state: latest
    
- name: "Install npm "
  become: yes
  apt:
    name: ["npm"]
    state: latest
    
- name: "Install pm2 "
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
    production: yes 
    
- name: "Create directory "
  become: yes
  shell: mkdir ~/web
  
- name: "Copy files "
  become: yes
  copy: 
    src: files/index.js
    dest: ~/web/index.js
    
- name: "Run server "
  become: yes
  shell: |
    pm2 start ~/web/index.js -f
    
  
 
   

